### ISSUE TITLE
Sniffing PROXY protocol is counter to specification with security implications

### ISSUE THREAD

**Issue by will0** [armon/go-proxyproto#11]
Per the [spec](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) the automatic detection of whether the PROXY protocol is in use is a "MUST not", because it allows a "major security breach".

> The receiver MUST NOT start processing the connection before it receives a
> complete and valid PROXY protocol header. This is particularly important for
> protocols where the receiver is expected to speak first (eg: SMTP, FTP or SSH).
> The receiver may apply a short timeout and decide to abort the connection if
> the protocol header is not seen within a few seconds (at least 3 seconds to
> cover a TCP retransmit).
> 
> The receiver MUST be configured to only receive the protocol described in this
> specification and MUST not try to guess whether the protocol header is present
> or not. This means that the protocol explicitly prevents port sharing between
> public and private access. Otherwise it would open a major security breach by
> allowing untrusted parties to spoof their connection addresses. The receiver
> SHOULD ensure proper access filtering so that only trusted proxies are allowed
> to use this protocol.

**Comment by jefferai** [comment]
The library takes a net.Listener, so necessarily separation of public/private ports must be done in a higher level application. The library allows you to define a source checker to ensure that only given IP addresses are trusted to specify PROXY, but that's defense in depth; ideally you set that *and* ensure via firewall rules and listener configuration that only trusted hosts can access that port in the first place.

**Comment by will0** [comment]
Perhaps you'd be open to a change in defaults such that only RFC 1918 addresses are allowed with a zero-initialized Listener, and default timeout of 3 seconds? I'm happy to put some work in.

**Comment by jefferai** [comment]
I'm not following the suggestion -- we don't allow a nil/zero-initialized listener (or rather, don't really check for it, which is a separate issue). How would you suggest knowing whether a listener is zero-initialized?

**Comment by will0** [comment]
By zero initialized, I mean where the ProxyHeaderTimeout and SourceCheck fields are not intialized in the Listener struct initializer - as in the example code:

```
// Create a listener
list, err := net.Listen("tcp", "...")

// Wrap listener in a proxyproto listener
proxyList := &proxyproto.Listener{Listener: list}
conn, err :=proxyList.Accept()
```

`nil` and `0` could be treated as uninitialized [as the Connection wrapper uses the values](https://github.com/armon/go-proxyproto/blob/master/protocol.go#L75-L84)

There would need to be a documentation update for the timeout, and potentially a `-1` or similar special case and constant for handling an infinite timeout.

**Comment by jefferai** [comment]
I don't really understand how those things are related. What does not providing a sourcecheck, which is optional, and also not a timeout, which is also optional, have to do with only allowing RFC1918 addresses?

**Comment by will0** [comment]
If someone copies the example code and deploys it reachable on the internet without the PROXY header always inserted, whether because its listening directly or because the load balancer is not correctly configured, the service will appear to work but addresses will be spoofable. From searching through github, this [appears to be a likely scenario](https://github.com/search?p=4&q=proxyproto.Listener&type=Code).

SourceCheck | No LB | LB with PROXY | LB without PROXY
-----|------|----------------|-------------------
Current default | Spoof | No Spoof           | Spoof
RFC1918 Only | No Public Spoof | No Spoof           | Spoof

RFC1918 Only means an attacker would at least need to already have access to initiate traffic apparently within private network space in order to spoof the PROXY header, which seems a rather material improvement in default behavior.

Fixing the last column would require never sniffing the protocol and being OK with the misconfiguration resulting in errors and failed connections. Currently in this configuration the source address is not meaningful.

**Comment by jefferai** [comment]
While your assessment is correct, I don't see a reason why you'd deploy a service in a publicly accessible way and turn on PROXY but then not have it behind a LB. I don't think there's any real use case for that. And as you have noted, in that instance you can spoof both the source address and a PROXY header. Disallowing PROXY in that case doesn't help the behavior, you just spoof the address without also adding a PROXY header.

On the other hand, making this behavior mandatory would mean that in cases where you have non-RFC1918 addresses but that are not publicly accessible this simply doesn't work. I worked at such a place for 8 years, so I know they exist.

**Comment by will0** [comment]
I'm coming from "misconfigured deployments are happening" rather than "why", but my guess as to why is people who have never heard of PROXY protocol being asked to implement it, finding this via search, and copy pasting the example code. Everything seems to work and then an attacker bypasses the LB because they are on a public VPC.
